# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-05-12 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200512_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='topic',
            new_name='tema',
        ),
    ]
